apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres 
spec:
  type: ClusterIP # Тип сервісу - доступний тільки всередині кластера
  ports:
    - port: 5432 
      targetPort: 5432 
  selector:
    app: postgres 